Update deploy-main-to-gcp.yml

diff --git a/.github/workflows/deploy-main-to-gcp.yml b/.github/workflows/deploy-main-to-gcp.yml
--- a/.github/workflows/deploy-main-to-gcp.yml
+++ b/.github/workflows/deploy-main-to-gcp.yml
@@ -30,9 +30,31 @@ jobs:
         run: |
           ssh -i ~/.ssh/id_rsa -T "$SSH_USER@$SSH_HOST" << 'EOF'
             set -e
-            cd "$APP_DIR"
+
+            echo "WHOAMI:"
+            whoami
+
+            echo "HOME DIR:"
+            echo $HOME
+
+            echo "APP_DIR VALUE:"
+            echo "$APP_DIR"
+
+            echo "PWD BEFORE CD:"
+            pwd
+
+            echo "TRYING TO CD INTO APP_DIR:"
+            cd "$APP_DIR" || { echo "FAILED TO CD INTO $APP_DIR"; exit 1;}
+
+            echo "PWD AFTER CD:"
+            pwd
+
+            echo "LISTING DIRECTORY CONTENTS:"
+            ls -la
+            
             git pull
             sudo npm ci
+            
             pm2 delete "$PM2_NAME" || true
             pm2 start -f app.mjs --name "$PM2_NAME"
             pm2 save
